### Get all credentials
GET http://localhost:3000/api/credentials
Authorization: 123

### Get single credential
GET http://localhost:3000/api/credentials/Wurstmann
Authorization: 123

### Add single credential
POST http://localhost:3000/api/credentials
Authorization: 123
Content-Type: application/json

{
    "service": "Twitter",
    "username": "Marcel",
    "password": "123456789"
}

### Update single credential
PUT http://localhost:3000/api/credentials/Twitter
Authorization: 123
Content-Type: application/json

{
    "service": "Wurstmann",
    "username": "Wurst",
    "password": "Mann"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/Wurstmann
Authorization: 123