### Get all credentials
GET http://localhost:3000/api/credentials

### Get single credential
GET http://localhost:3000/api/credentials/blub

### Add single credential
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "service": "bsdgadsg",
    "username": "Marcel",
    "password": "12345678"
}

### Update single credential
PUT http://localhost:3000/api/credentials/test
Content-Type: application/json

{
    "service": "Wurstmann",
    "username": "Wurst",
    "password": "Mann"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/test